# put all fingerprinted scancentral artifacts in single container
overrides:
  - pURL: "pkg:debricked/fingerprinting"
    version: "latest" # (optional: if left out, we will determine the version)
    fileRegexes: # (Rust regex)
      - "Libs/python/.*"